config/routes.rb
Kirisblog::Application.routes.draw do

    devise_for :users, :controllers => { :registrations => "users/registrations", :sessions => "users/sessions"}

  namespace :admin do

    resources :enquiries , :only =>["index","show"] do
        get "search",                                                    :on => :collection
    end
    resources :articles do
      get   "manage_comment_status",                                   :on => :member
      put   "manage_comment_status",                                   :on => :member
      get   "manage_article_status",                                   :on => :member
      put   "manage_article_status",                                   :on => :member
      get "search",                                                    :on => :collection
      get  "show_comment",                                             :on => :member
    end

    resources :users ,:only=>[:index, :show]  do
      get   "manage_status",                                   :on => :member
      put   "manage_status",                                   :on => :member
      get "search",                                                    :on => :collection
    end

    resources :subscribers do
      get   "manage_status",                                   :on => :member
      put   "manage_status",                                   :on => :member
      get "search",                                            :on => :collection
    end

    get "dashboard/index"
  end

  resources :home do
    get "feedback", :on => :collection
    get "about_me", :on => :collection
    get "welcome", :on => :collection
    get "contact_me", :on => :collection
    post "enquiry_mail", :on => :collection
    get "search",        :on => :collection
    get "load_theme", :on => :collection
    post "create_subscriber", :on => :collection
  end

   root :to => "home#index"

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments
validates :title, :presence => true
validates :description, :presence => true


   #  search bar in articles
  def self.search_articles(query)
    where("title LIKE ? or description LIKE ? ", "%#{query}%","%#{query}%" )
  end
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :get_details
  layout 'admin'
  # GET /admin/articles
  # GET /admin/articles.xml
  def index
    @articles = Article.paginate(:all,:page =>page, :per_page =>per_page , :order =>"created_at DESC")

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @articles }
    end
  end

  # GET /admin/articles/1
  # GET /admin/articles/1.xml
  def show
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @article }
    end
  end

  # GET /admin/articles/new
  # GET /admin/articles/new.xml
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @article }
    end
  end

  # GET /admin/articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /admin/articles
  # POST /admin/articles.xml
  def create
    @article = Article.new(params[:article])
    @article.category = "Rails"
    respond_to do |format|
      if @article.save
        format.html { redirect_to(admin_article_path(@article), :notice => 'Article was successfully created.') }
        format.xml  { render :xml => @article, :status => :created, :location => @article }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @article.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /admin/articles/1
  # PUT /admin/articles/1.xml
  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to(admin_article_path(@article), :notice => 'Article was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @article.errors, :status => :unprocessable_entity }
      end
    end
  end

  def manage_comment_status
    comment = Comment.find(params[:id])
     comment.toggle! :status
    redirect_to :back
    flash[:success] = "Status changed Succesfully"
  end

  def manage_article_status
    article = Article.find(params[:id])
     article.toggle! :status
    redirect_to :back
    flash[:success] = "Status changed Succesfully"
  end

  def search
    @articles = Article.search_articles(params[:search]).paginate(:all,:page =>page, :per_page =>per_page , :order =>"created_at DESC")
  end


  def show_comment
    @comment = Comment.find(params[:id])
  end

  # DELETE /admin/articles/1
  # DELETE /admin/articles/1.xml
=begin
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to(admin_articles_url) }
      format.xml  { head :ok }
    end
  end
=end

    protected

  def get_details
    ## method used to get required details in the layout sections and corresponding pages.
    @recent = Article.select("id,title").limit(5).order("created_at DESC")
  end
end

app/views/admin/articles/_form.html.erb
<%= javascript_include_tag "ckeditor/ckeditor" %>
<p>
  <table cellspacing="1" class="tablesorter"   style="width:50%;">
<%= form_for([:admin, @article]) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this admin_article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <tr>
      <td><%= f.label :title %></td>
      <td><%= f.text_area :title , :cols => 108, :rows=> 2%></td>
    </tr>


  </div>
  <div class="field">
    <tr>
      <td><%= f.label :description %></td>
      <td><%= f.cktext_area :description,  :width => 800, :height => 400 %></td>
    </tr>

  </div>
          <div class="field">
    <tr>
      <td>Likes</td>
      <td><%= f.text_field :feedback_yes %></td>
    </tr>

  </div>
          <div class="field">
    <tr>
      <td>Unlikes</td>
      <td><%= f.text_field :feedback_no %></td>
    </tr>

  </div>
  <div class="actions">
    <tr>
      <td colspan="2"><%= f.submit %></td>
    </tr>

  </div>

<% end %>
      </table>

app/views/admin/articles/_index.html.erb
<% title "Kiris Blog | Listing Articles" %>
<div class="list" id="template_category_list">
  <div class="list" id="admintable">
    <table width="100%">
      <tbody><tr><td align="left"><h3 align="left">Listing Articles</h3></td>
        <td align="right"><b><i>per page</i></b><%= per_page%> | <%= page_entries_info @articles %></td>
      </tr>
      </tbody>
    </table>

    <table cellspacing="1" class="tablesorter">
      <thead>
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Comments</th>
        <th>Likes</th>
        <th>Unlikes</th>
        <th></th>

      </tr>
      </thead>
      <tbody>

      <% @articles.each do |article| %>
          <tr class="<%= cycle( 'even','odd') %>">
            <td><%= highlight(truncate(article.title, :length =>75), params[:search]) %></td>
            <td><%=highlight(raw(truncate(article.description, :length =>100)), params[:search]) %></td>
            <td><center><%= article.comments.count %></center></td>
            <td><center><%= article.feedback_yes %></center></td>
            <td><center><%= article.feedback_no %></center></td>
            <td><%= link_to 'Show', admin_article_path(article) %> | <%= link_to 'Edit', edit_admin_article_path(article) %> |

              </span> <i id = "status_<%= article.id %>">   <%= link_to article.status? ? "Active" : "Inactive",manage_article_status_admin_article_path(:id => article.id)  %> </i></td>
          </tr>
      <% end %>

      </tbody>
    </table>
    <div style="width:auto; clear:both; margin:10px 0px 10px 0px; float:right; color:#0066FF;">
      <h4 align="right"><%= will_paginate @articles%></h4>
    </div>

  </div>
</div>

app/views/admin/articles/_sidebar_recent.html.erb
<div class="panel">
  <div class="caption">Recent Articles        </div>
  <div id="recently">
    <% @recent.each do |article| %>
        <li id="recent_article_<%= article.id %>" class="">
          <dt><%= link_to truncate(article.title, :length =>30),  admin_article_path(article) %></dt>
          <tt><br /></tt>
        </li>
    <% end %>
  </div>
</div>

app/views/admin/articles/_sidebar_top.html.erb
<div class="filters">
  <!--  Search bar -->
  <h4>Search Articles</h4>
  <div style="margin: 0px 0px 6px;">
    <%= form_tag(search_admin_articles_path, :method=>'get') do %>
    <table>
      <tr>
        <td><%= text_field_tag :search%></td>
        <td><%= submit_tag "Search"%> </td>
      </tr>
    </table>
    <% end %>
  </div>
</div>

app/views/admin/articles/edit.html.erb
<% title "Kiris Blog | Edit Article" %>
<div class="list" id="admintable">
  <table width="40%">
    <tbody><tr><td align="left"><h3 align="left">Update Article</h3></td>

    </tr>
    </tbody>
  </table>
</div>

<%= render 'form' %>

<%= link_to 'Show', @admin_article %> |
<%= link_to 'Back', admin_articles_path %>

app/views/admin/articles/new.html.erb
<% title "Kiris Blog | New Article" %>
<div class="list" id="admintable">
  <table width="40%">
    <tbody><tr><td align="left"><h3 align="left">New Article</h3></td>

    </tr>
    </tbody>
  </table>
</div>

<%= render 'form' %>

<%= link_to 'Back', admin_articles_path %>

app/views/admin/articles/search.html.erb
<% title "Kiris Blog | Search Articles" %>
<%= render "index" %>

app/views/admin/articles/show.html.erb
<% title "Kiris Blog |  Article" %>
<br />
<div class="title" style="border:none;"><span>Admin Details</span></div>
<table cellspacing="1" class="tablesorter" style="width:100%;">

  <tr><td width="10%"><b>Title</b></td>
    <td ><%= @article.title %></td></tr>
   <tr><td width="10%"><b>Likes</b></td>
    <td ><%= @article.feedback_yes %></td></tr>
   <tr><td width="10%"><b>Unlikes</b></td>
    <td ><%= @article.feedback_no %></td></tr>
  <tr><td width="10%"><b>Description</b></td>
    <td ><%=raw(@article.description)%></td></tr>

  <tr><td width="10%"><b>Created at</b></td>
    <td ><%= distance_of_time_in_words_to_now(@article.created_at, include_seconds = true) %> ago</td></tr>
  <tr><td width="10%"><b>Updated at</b></td>
    <td ><%= distance_of_time_in_words_to_now(@article.updated_at, include_seconds = true) %> ago</td></tr>
</table>


<%= link_to 'Edit', edit_admin_article_path(@article) %> |
<%= link_to 'Back', admin_articles_path %>

<div class="list" id="template_category_list">
  <div class="list" id="admintable">


    <table cellspacing="1" class="tablesorter">
      <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Description</th>
        <th>Status</th>

      </tr>
      </thead>
      <tbody>

      <%  @article.comments.each do |comment| %>
          <tr class="<%= cycle( 'even','odd') %>">
            <td><%= comment.name %></td>
            <td><%= comment.email %></td>
            <td><%=raw(truncate(comment.description, :length =>50)) %></td>
            <td>   </span> <i id = "status_<%= comment.id %>">   <%= link_to comment.status? ? "Active" : "Inactive",manage_comment_status_admin_article_path(:id => comment.id)  %> </i>  | <%= link_to "view", show_comment_admin_article_path(comment) %></td>
          </tr>
      <% end %>

      </tbody>
    </table>


  </div>
  </div>

app/views/admin/articles/show_comment.html.erb
<% title "Kiris Blog |  Comment" %>
<br />
<div class="title" style="border:none;"><span><%= @comment.article.title %></span></div>
<table cellspacing="1" class="tablesorter" style="width:100%;">

  <tr><td width="10%"><b>Name</b></td>
    <td ><%= @comment.name %></td></tr>
  <tr><td width="10%"><b>Email</b></td>
    <td ><%= @comment.email %></td></tr>
  <tr><td width="10%"><b>website</b></td>
    <td ><%= @comment.website %></td></tr>
  <tr><td width="10%"><b>Description</b></td>
    <td ><%=raw(@comment.description)%></td></tr>

  <tr><td width="10%"><b>Created at</b></td>
    <td ><%= distance_of_time_in_words_to_now(@comment.created_at, include_seconds = true) %> ago</td></tr>
  <tr><td width="10%"><b>Updated at</b></td>
    <td ><%= distance_of_time_in_words_to_now(@comment.updated_at, include_seconds = true) %> ago</td></tr>
</table>