config/routes.rb
Kirisblog::Application.routes.draw do

    devise_for :users, :controllers => { :registrations => "users/registrations", :sessions => "users/sessions"}

  namespace :admin do

    resources :enquiries , :only =>["index","show"] do
        get "search",                                                    :on => :collection
    end
    resources :articles do
      get   "manage_comment_status",                                   :on => :member
      put   "manage_comment_status",                                   :on => :member
      get   "manage_article_status",                                   :on => :member
      put   "manage_article_status",                                   :on => :member
      get "search",                                                    :on => :collection
      get  "show_comment",                                             :on => :member
    end

    resources :users ,:only=>[:index, :show]  do
      get   "manage_status",                                   :on => :member
      put   "manage_status",                                   :on => :member
      get "search",                                                    :on => :collection
    end

    resources :subscribers do
      get   "manage_status",                                   :on => :member
      put   "manage_status",                                   :on => :member
      get "search",                                            :on => :collection
    end

    get "dashboard/index"
  end

  resources :home do
    get "feedback", :on => :collection
    get "about_me", :on => :collection
    get "welcome", :on => :collection
    get "contact_me", :on => :collection
    post "enquiry_mail", :on => :collection
    get "search",        :on => :collection
    get "load_theme", :on => :collection
    post "create_subscriber", :on => :collection
  end

   root :to => "home#index"

end

app/views/layouts/admin/_footer.html.erb
 <% cache ("footer") do %>
<div id="footer">
    Powered by <a href="http://www.indigenius.com/" onclick="window.open(this.href);return false;">
    <b>Indigenius Solutions</b></a>
    © 2010-2011    
</div>
<% end %>

app/views/layouts/admin/_header.html.erb
 <% cache("header") do %>
    <div id="header">
        <div id="welcome"><!--  <b> <%#= current_administrator.username%> , Hospital_id : <%#= current_administrator.hospital_id%> , Location_id : <%#= current_administrator.location_id%></b>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; -->
            <b><%= Date.today.strftime("%d - %h - %Y ( %A )") %></b> <span id="welcome_username"></span>
            <span>&nbsp;&nbsp;</span>           
            |<%= link_to 'Profile'  %>  <!-- logged_in_user_profile_path-->
            |<%= link_to 'Logout', destroy_user_session_path, :method => :delete  %>  <!-- destroy_user_session_path -->
            <br /><br />
        </div>
        <h3><%= link_to image_tag("/images/Logo_main.png", :border => 0, :height=>"100px" ,:width=>"200px",:title => 'Kiris Blog'), root_path %></h3><!--root_path -->
    </div>

<% end %>

app/views/layouts/admin/_import_flash.html.erb
<% flash.each do |key, msg| %>
      <%=content_tag :div, msg, :class =>"flash_#{key}", :id => "app_flash"%>
 <% end %> 	




app/views/layouts/admin/_menu.html.erb
<div style="background-color:#1e4262; width:100%;">
  <!-- <div style="margin:0px; padding:0px 0px 0px 280px; float:left; background-color:#1e4262; width:79.3%; ">  -->
  <div style="margin:0px; padding:0px 0px 0px 280px;  background-color:#1e4262; ">

    <div id="tabs">

      <ul>
        <li><%= link_to "Dashboard",admin_dashboard_index_path,  :class=>(controller_name == 'dashboard' ? "active" : "")%></li>
        <li><%= link_to "Users",admin_users_path,  :class=>(controller_name == 'users' ? "active" : "") %></li>
        <li><%= link_to "Articles",admin_articles_path,  :class=>(controller_name == 'articles' ? "active" : "") %></li>
         <li><%= link_to "Subscribers",admin_subscribers_path,  :class=>(controller_name == 'subscribers' ? "active" : "") %></li>
         <li><%= link_to "Enquiries",admin_enquiries_path,  :class=>(controller_name == 'enquiries' ? "active" : "") %></li>

      </ul>

    </div>
  </div>
</div>