config/routes.rb
Kirisblog::Application.routes.draw do

    devise_for :users, :controllers => { :registrations => "users/registrations", :sessions => "users/sessions"}

  namespace :admin do

    resources :enquiries , :only =>["index","show"] do
        get "search",                                                    :on => :collection
    end
    resources :articles do
      get   "manage_comment_status",                                   :on => :member
      put   "manage_comment_status",                                   :on => :member
      get   "manage_article_status",                                   :on => :member
      put   "manage_article_status",                                   :on => :member
      get "search",                                                    :on => :collection
      get  "show_comment",                                             :on => :member
    end

    resources :users ,:only=>[:index, :show]  do
      get   "manage_status",                                   :on => :member
      put   "manage_status",                                   :on => :member
      get "search",                                                    :on => :collection
    end

    resources :subscribers do
      get   "manage_status",                                   :on => :member
      put   "manage_status",                                   :on => :member
      get "search",                                            :on => :collection
    end

    get "dashboard/index"
  end

  resources :home do
    get "feedback", :on => :collection
    get "about_me", :on => :collection
    get "welcome", :on => :collection
    get "contact_me", :on => :collection
    post "enquiry_mail", :on => :collection
    get "search",        :on => :collection
    get "load_theme", :on => :collection
    post "create_subscriber", :on => :collection
  end

   root :to => "home#index"

end

app/views/layouts/_import_flash.html.erb
<% flash.each do |key, msg| %>
      <%=content_tag :div, msg, :class =>"flash_#{key}", :id => "app_flash"%>
 <% end %> 	




app/views/layouts/_menu.html.erb
<ul>
      <li class="active"><a href="#" accesskey="1" title="">Home</a></li>
  <li><%= link_to "Flash Games",flash_games_home_index_path %></li>
      <li><a href="#" accesskey="2" title="">Contact us</a></li>
    
</ul>

app/views/layouts/_sidebar.html.erb
<div id="about-box"></div>
<ul>
  <li>
    <h2>Search Articles</h2>
    <ul>
      <li>
        <%= form_tag("/home/search", :method=>'get') do %>
            <table>
              <tr>
                <td><%= text_field_tag :search ,'',  :class=>"text", :size => 20 ,:style => " width: 150px;" %>
            <%= submit_tag "Search" ,:class => "blue_button"%> </td>
              </tr>
            </table>
        <% end %> </li>
    </ul>
  </li>
</ul>


<ul>
  <!-- this style will be remove on 2013 , this style is for open the tree view,  and class name replace with "trigger opened" to "trigger" -->
  <style>
      .level1{
          display: block;
      }
  </style>
  <br/>
  <li>
    <h2>Archive</h2>
    <ul style="padding: 0 0 0 25px">
      <li><div  >
        <% @articles_by_year.each do |year, posts| %>
            <a class="trigger opened" href="#"><%= year%> (<%= posts.count %> ) </a>
            <ul class="level1"  style="padding: 0 0 0 10px">
              <% posts.group_by { |post| post.created_at.strftime("%B") }.each do |month, articles| %>
                  <li><a class="trigger" href="#"><%= month %>  (<%= articles.count %>)</a>
                    <ul class="level2">
                      <% articles.each do |article| %>
                          <li style="width: 190px; "><%= link_to truncate(article.title, :length => 25), home_path(article.title), :title => article.title %></li>
                      <% end %>
                    </ul>
                  </li>
              <% end %>
            </ul>
            <div style="clear:both"></div>
        <% end %>
      </div></li>
    </ul>
  </li>


  <li>
    <h2>Recent Articles</h2>
    <ul>
      <% @recent_articles.each do |article| %>
          <li><%= link_to truncate(article.title, :length => 25),home_path(article.title), :title => article.title %></li>
      <% end %>
    </ul>
  </li>

  <br/>

  <li>
    <h2>Top Articles</h2>
    <ul>
      <% @top_articles.each do |article| %>
          <li><%= link_to truncate(article.title, :length => 25),home_path(article.title), :title => article.title %></li>
      <% end %>
    </ul>
  </li>
  <div  style="margin: 38px 0px 0px 0px;" >
    <ul>
      <li>
        <h2>Subscribe Articles</h2>
        <ul>
          <li>
            <%= form_for @subsciber, :url=> {:controller => "home", :action => "create_subscriber"}, :validate => true do |f| %>

                <p style="margin:12px 0px; width: 270px;"><b> Email</b><br/>  <%= f.text_field :email, :class=>"text"  ,:style => " width: 226px;" %>  </p>

                <p class="button" style="margin: 10px 1px 1px 92px;"><%= f.submit :class=>"blue_button", :value=>"Subscribe" %></p>
            <% end %>
          </li>
        </ul>
      </li>
    </ul>
  </div>

<li>
<h2></h2>
<ul>
 
<br/>
  <!--<iframe src="http://www.facebook.com/plugins/like.php?href=kiris.in&amp;layout=standard&amp;show_faces=true&amp;width=250&amp;action=like&amp;font=arial&amp;colorscheme=light&amp;height=80" style="border:none; overflow:hidden; width:250px; height:80px;" allowTransparency="true"></iframe>-->
      <div style="border: 1px;">
        <iframe src="http://www.facebook.com/plugins/like.php?href=kiris.in&amp;layout=standard&amp;show_faces=true&amp;width=450&amp;action=like&amp;font=arial&amp;colorscheme=light&amp;height=80" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:250px; height:80px;" allowTransparency="true"></iframe>
      </div>
      <br/>

    </ul>
  </li>
  </li>

<!--
  <li>

    <ul>


      <br>
      <a href="http://www.hitwebcounter.com/countersiteservices.php" title="Web Counter"
         target="_blank" style="font-family: Arial, Geneva , Helvetica, sans-serif;
              text-decoration: none ; color: #6D7A78; font-size: 12px;">
        <code> </code></a>
      
      <a href="http://www.hitwebcounter.com/" target="_blank">
        <img src="http://hitwebcounter.com/counter/counter.php?page=4453601&style=0019&nbdigits=6&type=ip&initCount=0" title="" Alt=""   border="0" >
      </a>


    </ul>
-->
 


</ul>

app/views/layouts/admin.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!-- START:jit -->
<html>
<head>
  <title><%= content_for?(:title) ? content_for(:title) : 'Kiris Blog' %></title>
  <link rel="shortcut icon" href="/favicon.png" />
  <%= stylesheet_link_tag 'admin_screen','tablesorter', :media => "all"  %>
  <%= javascript_include_tag :defaults  %>
  <link rel="shortcut icon" href="/images/favicon.png" />
  <%= csrf_meta_tag %>
</head>
<!-- END:jit -->

<body id="store">
<%= render :partial=>'layouts/admin/header' %>
<%= render :partial=>'layouts/admin/menu' %>
<!--START FLASH -->
<div id="flash" style="display: none;"></div>

<!-- END FLASH -->

<table class="tabbed" height="100%" width="100%" cellspacing="0" cellpadding="0">
  <tr>
    <!-- Start SIDE BAR -->
    <td id="sidebar" class="sidebar" valign="top">
      <%= render "sidebar_top" %>

        <!--  Ajax Radio buttons approved or suspended (Side bar) -->
        <div id="snapshot">
          <%#=render :partial=>'administrators/users/snapshot' %>
        </div>
        <!-- end -->

      </div>

        <%= render "sidebar_recent" %>



    </td>

    <!-- END SIDE BAR-->
    <td id="main" class="main" valign="top">
      <br />

      <br />
        <div class="title_tools"><abbr id="right_arrow">►</abbr>&nbsp;

				                 <%= link_to 'New Article', new_admin_article_path %>   &nbsp;&nbsp;&nbsp;
				    </div>

      <div class="title">
        <span><%= controller_name.capitalize %> Management</span>

        <img alt="Loading" id="loading" src="/images/spinner.gif" style="display: none;" width="16" height="16"/>
      </div>
      <%=render  'layouts/admin/import_flash'%>
      <%=yield%>
    </td>
  </tr>
</table>
<%=render :partial=>'layouts/admin/footer'%>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kirisblog</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/main_layout.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title><%= content_for?(:title) ? content_for(:title) : 'Kiris Blog' %></title>
  <%#= stylesheet_link_tag "default" %>
  <%# if session[:theme] == "blue" %>
  <% if action_name == "welcome" %>
      <%= stylesheet_link_tag "welcome", 'nivo-slider','nivo_default','nivo_style' %>
      <% else %>
  <%= stylesheet_link_tag "stylesheet_main", 'nivo-slider','nivo_default','nivo_style' %>
      <% end %>
  <%# else %>
  <%#= stylesheet_link_tag "stylesheet_green" %>
  <%# end %>
  <%= javascript_include_tag :defaults %>
  <%= javascript_include_tag 'rails.validations','jquery.nivo.slider' %>
  <link rel="shortcut icon" href="/images/favicon.png" />
</head>

<body class="homebg">

<!--header starts-->
<div id="header">
  <!--    <div style="float: right;color: white;" id="theme_selection">
      <%#= select_tag :theme  ,  options_for_select(["blue","green"]),  :include_blank => "select theme" %>
    </div>
    <div id="theme_result" style="color: white;float: right;">
          you selected <%#= session[:theme] %>    <%#= link_to "change theme", '#', :id => "change_theme" %>
    </div>-->
<!--  <%#= javascript_tag do %>
      window.selected_theme = "<%=j session[:theme] %>";
  <%# end %>-->
  <div class="logo">
    <h1>  <%= link_to image_tag("/images/Logo_main.png"), root_path  %></h1>
  </div>
  <div class="right">
    <div id="navigation">
      <ul>
        <li class="first"><%= link_to "Home", root_path %></li>
        <li><a href="/home/about_me">About</a></li>

        <li class="last"><a href="/home/contact_me">Contact</a></li>
      </ul>
    </div>
  </div>
</div>
<!--header ends-->


<div id="wrapper">

  <!--entire container starts-->
  <div id="container">
    <!--middle starts-->
    <div id="wrapper1">


 
      <div class="slider-wrapper theme-default"  style="height:240px;">
        <div id="slider" class="nivoSlider">
          <img src="/images/slider/5.jpg" data-thumb="images/toystory.jpg" alt="" />
          <a href="http://kiris.in"><img src="/images/slider/4.jpg" data-thumb="/images/slider/2.jpg" alt="" title="This is an example of a caption" /></a>
          <img src="/images/slider/6.jpg" data-thumb="/images/slider/02.jpg" alt="" data-transition="slideInLeft" />
          <img src="/images/slider/3.jpg" data-thumb="/images/slider/3.jpg" alt="" title="#htmlcaption" />
          <img src="/images/slider/7.jpg" />
 
        </div>
        <div id="htmlcaption" class="nivo-html-caption">
          <strong>This</strong> is an example of a <em>HTML</em> caption with <a href="http://kiris.in">Read more</a>.
        </div>
      </div>

    </div>
    <div id="middle_container">



      <div class="left">
        <%= render "/layouts/import_flash" %>
        <%= yield %>

      </div>

      <div class="right">
        <div id="sidebar">
          <%= render "/layouts/sidebar" %>
        </div>
      </div>

    </div>
    <!--middle ends-->
    <!--footer starts-->
    <div id="footer_container">
      <ul>
        <li class="first"><a href="/home">Home</a></li>
        <li><a href="/home/about_me">About</a></li>

        <li class="last"><a href="/home/contact_me">Contact</a></li>
      </ul>
      Kiris © 2012.All rights reserved
    </div>
    <!--footer ends-->
  </div>
</div>
</body>
</html>
<script type="text/javascript">
    $(window).load(function() {
        $('#slider').nivoSlider();
    });
</script>

app/views/layouts/welcome.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">


  <title> Kiris Blog</title>

  <%= stylesheet_link_tag "welcome", 'nivo-slider','nivo_default','nivo_style', :cache => "cache_styles" %>
  


  <link rel="shortcut icon" href="/images/favicon.png" />
</head>
<body id="home">

<!-- Start HEADER -->
<div id="menu" style="float: right;">
  <ul id="nav">
    <li class="yellow"><%= link_to "Home", welcome_home_index_path %></li>
    <li class="blue"><%= link_to "Blog", home_index_path %></li>
    <li class="red"><%= link_to "About", about_me_home_index_path %></li>
    <li class="green"> <%= link_to "Contact", contact_me_home_index_path %></li>
  </ul>
</div>
<div id="header">

  <div id="logo" style="clear: left;">
    <img class="logo" src="/images/Logo_main.png" alt="kiris" width="274" height="105">
  </div>
</div>
<!-- End HEADER -->

<!-- Start FEATURE -->
<div id="header_curve"></div>
<!-- End FEATURE -->

<!-- Start CONTENT CONTAINER -->
<div id="wrapper">
  <div id="contentArea">
    <div id="wrapper1">
      <div class="slider-wrapper theme-default"  style="height:240px;">
        <div id="slider" class="nivoSlider">
          <img src="/images/slider/5.jpg" data-thumb="/images/toystory.jpg" alt="" />
          <a href="http://kiris.in"><img src="/images/slider/4.jpg" data-thumb="/images/slider/2.jpg" alt="" title="This is an example of a caption" /></a>
          <img src="/images/slider/6.jpg" data-thumb="/images/slider/02.jpg" alt="" data-transition="slideInLeft" />
          <img src="/images/slider/3.jpg" data-thumb="/images/slider/3.jpg" alt="" title="#htmlcaption" />
          <img src="/images/slider/7.jpg" />

        </div>
        <div id="htmlcaption" class="nivo-html-caption">
          <strong>This</strong> is an example of a <em>HTML</em> caption with <a href="http://kiris.in">Read more</a>.
        </div>
      </div>
    </div>
    <%= render "/layouts/import_flash" %>


<!-- AddThis Button END -->

    <%= yield %>

  </div>
  <!-- END CONTENT -->
</div>
 
<div id="footerContainer">
        <!-- AddThis Button BEGIN -->
<div class="addthis_toolbox addthis_floating_style addthis_counter_style" style="left:10px;top:235px; border-radius: 8px 8px 8px 8px;">
<a class="addthis_button_facebook_like" fb:like:layout="box_count" addthis:url="http://kiris.in"></a>
<a class="addthis_button_tweet" tw:count="vertical" addthis:url="http://kiris.in"></a>
<a class="addthis_button_google_plusone" g:plusone:size="tall" addthis:url="http://kiris.in"></a>
<a class="addthis_counter"></a>
</div>
  <div id="footerArea"></div>
</div>
<!-- End FOOTER -->
<script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=xa-50028df1079f7e61"></script>
<%= javascript_include_tag :defaults, 'rails.validations','jquery.nivo.slider'  %>
 
 
</body>
</html>